config/routes.rb
Rails.application.routes.draw do
  get 'contacts' => 'contacts#new'
  post 'contacts' => 'contacts#create'

  get 'home/index'
  get 'home/sobremi'

  root 'home#index'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :content

  validates :name, presence: true
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates_length_of :content, :maximum => 500
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contact = Contact.new(contact_params)
  end
  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    if @contact.valid?
      ContactMailer.new_message(@contact).deliver_now
      redirect_to(contacts_path , :notice => "Message was successfully sent.")
    else
      flash.now.alert = "Please fill all fields."
      render :new
    end
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def contact_params
    params.require(:contact).permit(:name, :email, :body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def sobremi
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sobremi_helper.rb
module SobremiHelper
end

app/views/contacts/_form.html.erb
<br><br>
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>
      <ul>
        <% @contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-xs-5 center-block">
      <div class="field">
        <%= f.text_field :name, placeholder:"Name", class:"form-control font-size-15"%>
      </div>
      <br>
      <div class="field">
        <%= f.text_field :email, placeholder:"Email", class:"form-control font-size-15"%>
      </div>
      <br>
      <div class="field">
        <%= f.text_area :body, placeholder:"bla bla bla..", style: "height: 270px", class:"form-control font-size-15"%>
      </div>
      <br>
      <div class="actions text-center">
        <%= f.submit "Send", class:"btn background-turquesa btn-lg font-size-20"%>
      </div>
    <% end %>
</div>

app/views/contacts/new.html.erb
<h1 class="Dancing Dancing-title text-center">Ponte en contacto conmigo</h1>
<%= render "form"%>

app/views/home/index.html.erb
<h1 class="Dancing Dancing-title text-center">Mis pasiones</h1>

<div class="card-deck-wrapper col-xs-12 col-sm-8 col-md-10 center-block padding-top-2">
  <div class="card-deck">
    <div class="card animated fadeInDown">
      <img class="card-img-top img-responsive" alt="Responsive image" src="/img/code.png" alt="Card image cap">
      <div class="card-block">
        <h4 class="card-title">Programar</h4>
        <p class="card-text">Creo mis ideas y soluciones que necesito.</p>
        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      </div>
    </div>
    <div class="card delay-1 animated fadeInDown">
      <img class="card-img-top img-responsive" alt="Responsive image" src="/img/travel.jpg" alt="Card image cap">
      <div class="card-block">
        <h4 class="card-title">Recorrer el mundo</h4>
        <p class="card-text">La vida está hecha para vivirla y el mundo para recorrerlo.</p>
        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      </div>
    </div>
    <div class="card delay-2 animated fadeInDown">
      <img class="card-img-top img-responsive" alt="Responsive image" src="/img/diy.png" alt="Card image cap">
      <div class="card-block">
        <h4 class="card-title">Manualidades</h4>
        <p class="card-text">.</p>
        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      </div>
    </div>
  </div>
</div>

app/views/home/sobremi.html.erb
<h1 class="Dancing Dancing-title text-center">This is me</h1>
<div class="col-xs-12 col-sm-6 col-md-8 center-block padding-top-2">
  <div class="animated pulse">
    <img class="img-border-1em img-responsive" alt="Responsive image" src="/img/18-.jpg" alt="Card image cap">
  </div>
</div>

app/views/layouts/application.html.erb
<!--pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start-->
<!DOCTYPE html>
<html lang="es">
  <head>
    <title>M4riacg</title>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <!--Frameworks-->
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="https://www.atlasestateagents.co.uk/javascript/tether.min.js"></script><!-- Tether for Bootstrap -->
    <script src="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.min.js"></script><!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/animatecss/3.5.1/animate.min.css"></link rel="stylesheet">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css">
  <!--Iconos-->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <!--Fuentes-->
  <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Dancing+Script' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Sarina' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Damion' rel='stylesheet' type='text/css'>
  <!--Enlaces de Ruby-->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <nav class="navbar navbar-default navbar-fixed-top background-turquesa" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav Montserrat">
          <li><%= link_to "Inicio", home_index_path%></li>
          <li><%= link_to "Sobre mi", home_sobremi_path%></li>
          <li><%= link_to "Contacto", contacts_path%></li>
        </ul>
      </div>
    </nav>
  </header>
  <main>
    <hr>
    <hr>
    <div class="container-fluid">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </main>
  <footer class="footer white">
    <hr />
    <div class="container">
      <div class="row">
        <div class="col-sm-8">© 2016 TODOS LOS DERECHOS RESERVADOS</div>
        <div class="col-sm-4" style="padding-bottom: 10px;">
          <a href="https://www.facebook.com/MariaCalzadaGonzalezPMI">
            <i class="fa fa-facebook-square fa-2x"></i>
          </a>
          <a href="https://www.instagram.com/m4riacg/" style="padding-left: 10px;">
            <i class="fa fa-instagram fa-2x"></i>
          </a>
        </div>
      </div>
    </div>
  </footer>
</body>
</html>